[package]
name = "coaptic-fuzz"
version = "0.0.0"
edition = "2024"
publish = false

[package.metadata]
cargo-fuzz = true

[workspace]

[dependencies]
libfuzzer-sys = "0.4"
coaptic = { path = "../coaptic", features = ["oscore"] }

[[bin]]
name = "datagram"
path = "fuzz_targets/datagram.rs"
test = false
doc = false
bench = false

[[bin]]
name = "cbor"
path = "fuzz_targets/cbor.rs"
test = false
doc = false
bench = false

[[bin]]
name = "oscore"
path = "fuzz_targets/oscore.rs"
test = false
doc = false
bench = false
